remove references to non-existant drawable resources
This just removes code that references drawable resources that do not exist
at all in this git repo.  Building OsmAnd with the current version of
Android Studio refused to run the app because of the errors related to
these missing resources.

:OsmAnd:compileFreeGoogleplayArmv5DebugJava
/media/share/code/osmandapp/Osmand/OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java:687: error: cannot find symbol
					return uiCtx.getResources().getDrawable(R.drawable.mx_highway_speed_camera);
					                                                  ^
  symbol:   variable mx_highway_speed_camera
  location: class drawable
/media/share/code/osmandapp/Osmand/OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java:689: error: cannot find symbol
					return uiCtx.getResources().getDrawable(R.drawable.mx_barrier_border_control);
					                                                  ^
  symbol:   variable mx_barrier_border_control
  location: class drawable
/media/share/code/osmandapp/Osmand/OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java:703: error: cannot find symbol
					return uiCtx.getResources().getDrawable(R.drawable.mx_barrier_toll_booth);
					                                                  ^
  symbol:   variable mx_barrier_toll_booth
  location: class drawable
/media/share/code/osmandapp/Osmand/OsmAnd/src/net/osmand/plus/views/RouteLayer.java:128: error: cannot find symbol
				Bitmap originalArrowUp = BitmapFactory.decodeResource(view.getResources(), R.drawable.h_arrow, null);
				                                                                                     ^
  symbol:   variable h_arrow
  location: class drawable
/media/share/code/osmandapp/Osmand/OsmAnd/src/net/osmand/plus/activities/search/SearchPoiFilterActivity.java:160: error: cannot find symbol
					icon.setImageResource(R.drawable.mx_user_defined);
					                                ^
  symbol:   variable mx_user_defined
  location: class drawable